# Generated by Django 3.1.2 on 2020-10-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_token', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='post_token')),
                ('title', models.CharField(max_length=50, verbose_name='Post Title')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Post pusblied Date')),
                ('view_count', models.IntegerField(default=0, verbose_name='view count')),
                ('like_count', models.IntegerField(default=0, verbose_name='like count')),
                ('image', models.CharField(blank=True, max_length=150, verbose_name='Sample image link')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_token', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='answer_token')),
                ('content', models.TextField(verbose_name='Answer content')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Post pusblied Date')),
                ('like_count', models.IntegerField(default=0, verbose_name='like count')),
                ('post_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.post')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
