# Generated by Django 3.1.2 on 2020-10-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('userid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('user_email', models.EmailField(blank=True, max_length=100)),
                ('phonenumber', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
